- name: command vs shell module example
  hosts: local
  connection: local
  tasks:
    - name: Run a simple command
      ansible.builtin.command: echo "Hello, World!"
      register: command_output

    - name: Display command output
      ansible.builtin.debug:
        msg: "{{ command_output }}"

    - name: Run a shell command with pipes
      ansible.builtin.shell: "cat /etc/passwd | grep root"
      register: shell_output

    - name: Display shell output
      ansible.builtin.debug:
        msg: "{{ shell_output }}"

    - name: Using command module on shell commands (fails)
      ansible.builtin.command: "cat /etc/passwd | grep root"
      register: command_fail_output

    - name: Display command fail output
      ansible.builtin.debug:
        msg: "{{ command_fail_output }}"
